[package]
name = "tepe"
version = "0.0.0"
authors = ["Hermitter"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
teloxide = "0.2.0"
log = "0.4.8"
tokio = "0.2.11"
pretty_env_logger = "0.4.0"
structopt = "0.3.7"
clap = "2.33.1"
lazy_static = "1.4.0"