[package]
name = "tepe"
version = "0.0.0"
authors = ["Hermitter"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
teloxide = "0.2.0"
tokio = "0.2.11"
clap = {version = "2.33.1", features = ["yaml"]}
lazy_static = "1.4.0"